name: GitFromPythonToFirebase
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 08 * * *'
    - cron: '0 1 * * *'
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python pythontofirebase
      run: |
        python3 pythontofirebase.py